spring:
  profiles:
    active: dev
cloud:
  aws:
    stack:
      auto: false
server:
  #port: 8081
  servlet:
    context-path: /backend-for-frontend
service:
  dns: http://internal-ma-tokuyamar-private-alb-236632658.ap-northeast-1.elb.amazonaws.com
  #dns: http://localhost:8080/